baseURL                          = "https://elliotalexander.uk/"   # Your domain name. Must end with "/"
theme                            = "introduction"
DefaultContentLanguage           = "en"                    # Default language for multilingual sites
# disqusshortname                 = ""                     # https://gohugo.io/content-management/comments
# googleAnalytics                 = ""                     # https://gohugo.io/templates/internal/#google-analytics

[params]
    themeStyle                   = "dark"                 # Choose "light" or "dark"
    favicon                      = "/img/fav.ico"          # Path to favicon file
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    customCSS                  = []             # Include custom css files placed under assets/
    customJS                   = []              # Include custom JavaScript files placed under assets/

    # Configure the home page
    [params.home]
        introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects
        localTime                = false # Show your current local time in contact section

    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

    [params.share]
        twitter                  = true
        facebook                 = true

    [[params.social]]
        url   = "https://twitter.com/elliotalex97"
        icon  = "twitter" 
        icon_pack = "fab"
    [[params.social]]
        url   = "https://www.linkedin.com/in/elliotalexander97/"
        icon  = "linkedin-in" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url = "mailto:elliot.alex.97@gmail.com"  # For a direct email link, use "mailto:test@example.org".
        icon = "paper-plane" # icon name without the 'fa-'
        icon_pack = "fas"
    [[params.social]]
        url   = "https://open.spotify.com/user/elllzman619"
        icon  = "spotify" # icon name without the 'fa-'
        icon_pack = "fab"

[taxonomies]
  tag = "tags"
  series = "series"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    # For styles, see https://xyproto.github.io/splash/docs/longer/all.html
    style = "friendly"
    tabWidth = 4

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-gb"
        contentDir       = "content/en"
        weight           = 0
        title            = "Elliot Alexander"
        [languages.en.params]
            description  = "Elliot Alexander's Personal Site"   # Max 160 characters show in search results
            # footerText   =                       # Text to override default footer text (markdown allowed)


[deployment]
    order = [".jpg$", ".gif$"]

[[deployment.targets]]
    name = "s3"
    URL = "s3://www.elliotalexander.uk?region=eu-west-2"
    cloudFrontDistributionID = "E15SEUHZ0DJLR5"


