version: 2.1

orbs:
    hugo: circleci/hugo@1.3.0
    node: circleci/node@5.0.2
    terraform: circleci/terraform@1.1.0

jobs:
    install:
        working_directory: "~/tmp"
        docker:
            - image: cimg/base:stable
        steps:
            - checkout
            - hugo/install:
                version: '0.96.0'
            - node/install:
                install-yarn: true
                node-version: '16.13'
            - run: node --version
            - run:
                name: Install PostCSS and Autoprefixer.
                command: >
                    npm i -g postcss postcss-cli autoprefixer
            - run:
                command: |
                    if [ -f ".gitmodules" ]; then
                      git submodule sync
                      git submodule update --init --recursive
                    fi
                name: Checkout Submodules if Needed
            - run:
                name: Run Hugo Build
                command: |
                    hugo -v -s . -d public
            - persist_to_workspace:
                root: "~/tmp"
                paths:
                    - public
workflows:
    build:
        jobs:
          - install
    deploy_infrastructure:
        jobs:
          - terraform/fmt:
              checkout: true
              context: terraform
          - terraform/validate:
              checkout: true
              context: terraform
              requires:
                - terraform/fmt
          - terraform/plan:
              checkout: true
              context: terraform
              persist-workspace: true
              requires:
                - terraform/validate
          - terraform/apply:
              attach-workspace: true
              context: terraform
              filters:
                branches:
                  only: master
              requires:
                - terraform/plan
