version: 2.1
orbs:
    hugo: circleci/hugo@1.3.0
    node: circleci/node@5.0.2

jobs:
    install:
        docker:
            - image: cimg/base:stable
        steps:
            - checkout
            - hugo/install:
                version: '0.96.0'
            - node/install:
                install-yarn: true
                node-version: '16.13'
            - run: node --version
            - run:
                command: >
                    npm i -g postcss postcss-cli autoprefixer
            - run:
                command: |
                    if [ -f ".gitmodules" ]; then
                      git submodule sync
                      git submodule update --init --recursive
                    fi
                name: Checkout Submodules if Needed
            - run:
                command: |
                    hugo -v -s . -d public

workflows:
    build:
        jobs:
            - install


