version: 2.1

orbs:
    hugo: circleci/hugo@1.3.0
    node: circleci/node@5.0.2
    terraform: circleci/terraform@3.0.1
    aws-s3: circleci/aws-s3@3.0.0

jobs:
    install:
        working_directory: "~/tmp"
        docker:
            - image: cimg/base:stable
        steps:
            - checkout
            - hugo/install:
                version: '0.96.0'
            - node/install:
                install-yarn: true
                node-version: '16.13'
            - run: node --version
            - run:
                name: Install PostCSS and Autoprefixer.
                command: >
                    npm i -g postcss postcss-cli autoprefixer
            - run:
                command: |
                    if [ -f ".gitmodules" ]; then
                      git submodule sync
                      git submodule update --init --recursive
                    fi
                name: Checkout Submodules if Needed
            - run:
                name: Run Hugo Build
                command: |
                    hugo -v -s . -d public
            - persist_to_workspace:
                root: "~/tmp"
                paths:
                    - public
    plan:
        working_directory: "~/workspace"
        docker:
            - image: cimg/base:stable
        steps:
            - checkout
            - attach_workspace:
                at: /tmp/workspace
            - run:
                command: ls /tmp/workspace/public
                name: List files to push
            - run:
                command: ls
                name: List files in workspace
            - terraform/install:
                terraform_version: 1.1.7
            - terraform/fmt:
                path: "terraform/deployment"
            - terraform/validate:
                path: "terraform/deployment"
            - terraform/plan:
                path: "terraform/deployment"
    deploy:
        working_directory: "~/workspace"
        docker:
            - image: cimg/base:stable
        steps:
            - checkout
            - terraform/install:
                terraform_version: 1.1.7
            - terraform/apply:
                path: "terraform/deployment"
            - run:
                command: |
                    export AWS_ACCESS_KEY_ID=`terraform output id | sed "s/\"//g"
                    export AWS_SECRET_ACCESS_KEY=`terraform output secret | sed "s/\"//g"
                name: Switch AWS Credentials
    sync:
        working_directory: "~/workspace"
        docker:
            - image: cimg/base:stable
        steps:
            - checkout
            - attach_workspace:
                at: /tmp/workspace
            - aws-s3/sync:
                arguments: |
                    --acl public-read \
                    --sse AES256
                from: /tmp/workspace
                to: s3://elliotalexander.uk/


workflows:
    build:
        jobs:
          - install
          - plan:
              name: "pre-deploy"
              requires:
                - install
          - hold:
              name: "prod-deploy-approval"
              type: "approval"
              requires: ["pre-deploy"]
          - deploy:
              name: "Terraform deploy"
              requires: ["prod-deploy-approval"]
          - hold:
              name: "prod-sync-approval"
              type: "approval"
              requires: ["pre-deploy"]
          - sync:
              name: "S3 Sync"
              requires: ["prod-sync-approval"]
