version: 2.1
orbs:
    hugo: circleci/hugo@1.3.0

jobs:
    install:
        docker:
            - image: circleci/node@5.0.2
        steps:
            - checkout
            - hugo/install:
                version: '0.96.0'
            - run:
                command: >
                    npm i -g postcss postcss-cli autoprefixer
            - run:
                command: |
                    if [ -f ".gitmodules" ]; then
                      git submodule sync
                      git submodule update --init --recursive
                    fi
                name: Checkout Submodules if Needed
            - run:
                command: |
                    hugo -v -s . -d public

workflows:
    build:
        jobs:
            - install


