version: 2.1

orbs:
    hugo: circleci/hugo@1.3.0
    node: circleci/node@5.0.2
    terraform: circleci/terraform@3.0.1

jobs:
    install:
        working_directory: "~/tmp"
        docker:
            - image: cimg/base:stable
        steps:
            - checkout
            - hugo/install:
                version: '0.96.0'
            - node/install:
                install-yarn: true
                node-version: '16.13'
            - run: node --version
            - run:
                name: Install PostCSS and Autoprefixer.
                command: >
                    npm i -g postcss postcss-cli autoprefixer
            - run:
                command: |
                    if [ -f ".gitmodules" ]; then
                      git submodule sync
                      git submodule update --init --recursive
                    fi
                name: Checkout Submodules if Needed
            - run:
                name: Run Hugo Build
                command: |
                    hugo -v -s . -d public
            - persist_to_workspace:
                root: "~/tmp"
                paths:
                    - public
    deploy:
        working_directory: "~/workspace"
        docker:
            - image: cimg/base:stable
        steps:
            - checkout
            - attach_workspace:
                at: /tmp/workspace
            - run:
                command: ls /tmp/workspace/public
                name: List files to push
            - run:
                command: ls
                name: List files in workspace
            - terraform/install:
                terraform_version: 1.1.7
            - terraform/fmt:
                path: "terraform"
            - terraform/validate:
                path: "~/workspace/terraform"
            - terraform/plan:
                path: "~/workspace/terraform"

workflows:
    build:
        jobs:
          - install
          - deploy:
              requires:
                - install
