version: 2.1
orbs:
    hugo: circleci/hugo@1.3.0

jobs:
    install:
        docker:
          - image: cimg/base
        steps:
            - hugo/install:
                version: '0.55'
            - run: ls -lah my-site


workflows:
    build:
        jobs:
            - install


