version: 2.1
orbs:
    hugo: circleci/hugo@1.3.0
workflows:
    build:
        jobs:
            - run: npm i -g postcss postcss-cli autoprefixer
            - hugo/build:
                html-proofer: true
                version: '0.55'


