version: 2.1
orbs:
    hugo: circleci/hugo@1.3.0

jobs:
    install:
        docker:
            - image: cimg/base:stable
        steps:
            - checkout
            - hugo/install:
                version: '0.96.0'
            - run:
                command: >
                    npm i -g postcss postcss-cli autoprefixer

workflows:
    build:
        jobs:
            - install


